import {
  Calendar,
  CalendarX,
  CalendarCheck,
  Clock,
  UserPlus,
  UserCheck,
  UserX,
  MessageSquare,
  ClipboardList,
  ClipboardCheck,
  FileText,
  FileCheck,
  Target,
  Plus,
  Unlink,
  BookOpen,
  MessageCircle,
  AlertTriangle,
  CreditCard,
  type LucideIcon,
} from 'lucide-react';

export const NOTIFICATION_ICON_MAP: Record<string, LucideIcon> = {
  BOOKING_CREATED: Calendar,
  BOOKING_CANCELLED: CalendarX,
  BOOKING_COMPLETED: CalendarCheck,
  BOOKING_REMINDER: Clock,
  CONNECTION_REQUEST: UserPlus,
  CONNECTION_ACCEPTED: UserCheck,
  CONNECTION_DECLINED: UserX,
  NEW_MESSAGE: MessageSquare,
  PLAN_ASSIGNED: ClipboardList,
  PLAN_UNASSIGNED: ClipboardCheck,
  ONBOARDING_SUBMITTED: FileText,
  ONBOARDING_REVIEWED: FileCheck,
  GOAL_CREATED: Plus,
  GOAL_COMPLETED: Target,
  CLIENT_DISCONNECTED: Unlink,
  DIARY_ENTRY: BookOpen,
  DIARY_COMMENT: MessageCircle,
  TRIAL_EXPIRING: AlertTriangle,
  PAYMENT_FAILED: CreditCard,
};
