export const MUSCLE_GROUP_OPTIONS = [
  { value: 'CHEST', label: 'Chest' },
  { value: 'BACK', label: 'Back' },
  { value: 'SHOULDERS', label: 'Shoulders' },
  { value: 'BICEPS', label: 'Biceps' },
  { value: 'TRICEPS', label: 'Triceps' },
  { value: 'FOREARMS', label: 'Forearms' },
  { value: 'ABS', label: 'Abs' },
  { value: 'OBLIQUES', label: 'Obliques' },
  { value: 'QUADS', label: 'Quads' },
  { value: 'HAMSTRINGS', label: 'Hamstrings' },
  { value: 'GLUTES', label: 'Glutes' },
  { value: 'CALVES', label: 'Calves' },
  { value: 'FULL_BODY', label: 'Full Body' },
  { value: 'CARDIO', label: 'Cardio' },
] as const;

export const COMMON_EQUIPMENT = [
  'Barbell',
  'Dumbbell',
  'Kettlebell',
  'Resistance Band',
  'Cable Machine',
  'Smith Machine',
  'Pull-up Bar',
  'Bench',
  'EZ Bar',
  'Medicine Ball',
  'Stability Ball',
  'Foam Roller',
  'TRX',
  'Bodyweight',
  'Treadmill',
  'Rowing Machine',
  'Stationary Bike',
  'Battle Ropes',
  'Box/Step',
  'Leg Press',
] as const;
