import type { ThemePreset, SectionTypeConfig } from './website.types';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'default',
    name: 'Clean',
    description: 'Minimal and modern, matches the Fitnassist palette',
    colors: {
      background: '0 0% 100%',
      foreground: '222.2 84% 4.9%',
      primary: '222.2 47.4% 11.2%',
      primaryForeground: '210 40% 98%',
      secondary: '210 40% 96.1%',
      secondaryForeground: '222.2 47.4% 11.2%',
      accent: '210 40% 96.1%',
      accentForeground: '222.2 47.4% 11.2%',
      muted: '210 40% 96.1%',
      mutedForeground: '215.4 16.3% 46.9%',
      card: '0 0% 100%',
      cardForeground: '222.2 84% 4.9%',
      border: '214.3 31.8% 91.4%',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    borderRadius: '0.5rem',
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'Dark background with bright accents',
    colors: {
      background: '224 71% 4%',
      foreground: '213 31% 91%',
      primary: '47 96% 53%',
      primaryForeground: '224 71% 4%',
      secondary: '222 47% 11%',
      secondaryForeground: '213 31% 91%',
      accent: '47 96% 53%',
      accentForeground: '224 71% 4%',
      muted: '223 47% 11%',
      mutedForeground: '215 16% 47%',
      card: '224 71% 7%',
      cardForeground: '213 31% 91%',
      border: '216 34% 17%',
    },
    fonts: { heading: 'Montserrat', body: 'Inter' },
    borderRadius: '0.375rem',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Serif fonts with muted, refined tones',
    colors: {
      background: '30 25% 97%',
      foreground: '20 14% 15%',
      primary: '20 14% 15%',
      primaryForeground: '30 25% 97%',
      secondary: '30 15% 92%',
      secondaryForeground: '20 14% 15%',
      accent: '24 70% 45%',
      accentForeground: '30 25% 97%',
      muted: '30 15% 92%',
      mutedForeground: '20 10% 50%',
      card: '30 25% 99%',
      cardForeground: '20 14% 15%',
      border: '30 15% 88%',
    },
    fonts: { heading: 'Playfair Display', body: 'Lora' },
    borderRadius: '0.25rem',
  },
  {
    id: 'sporty',
    name: 'Sporty',
    description: 'High contrast with geometric feel',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 9%',
      primary: '346 77% 50%',
      primaryForeground: '0 0% 100%',
      secondary: '210 17% 95%',
      secondaryForeground: '0 0% 9%',
      accent: '346 77% 50%',
      accentForeground: '0 0% 100%',
      muted: '210 17% 95%',
      mutedForeground: '0 0% 45%',
      card: '0 0% 100%',
      cardForeground: '0 0% 9%',
      border: '0 0% 90%',
    },
    fonts: { heading: 'Oswald', body: 'Roboto' },
    borderRadius: '0rem',
  },
  {
    id: 'natural',
    name: 'Natural',
    description: 'Earth tones with rounded, organic feel',
    colors: {
      background: '40 33% 97%',
      foreground: '150 10% 15%',
      primary: '152 44% 35%',
      primaryForeground: '40 33% 97%',
      secondary: '40 20% 92%',
      secondaryForeground: '150 10% 15%',
      accent: '152 44% 35%',
      accentForeground: '40 33% 97%',
      muted: '40 20% 92%',
      mutedForeground: '150 5% 50%',
      card: '40 33% 99%',
      cardForeground: '150 10% 15%',
      border: '40 15% 88%',
    },
    fonts: { heading: 'Nunito', body: 'Nunito Sans' },
    borderRadius: '1rem',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean with gradient accents',
    colors: {
      background: '0 0% 100%',
      foreground: '240 10% 10%',
      primary: '262 83% 58%',
      primaryForeground: '0 0% 100%',
      secondary: '240 5% 96%',
      secondaryForeground: '240 10% 10%',
      accent: '262 83% 58%',
      accentForeground: '0 0% 100%',
      muted: '240 5% 96%',
      mutedForeground: '240 4% 46%',
      card: '0 0% 100%',
      cardForeground: '240 10% 10%',
      border: '240 6% 90%',
    },
    fonts: { heading: 'Poppins', body: 'Inter' },
    borderRadius: '0.75rem',
  },
];

export const SECTION_TYPES: SectionTypeConfig[] = [
  {
    type: 'HERO',
    label: 'Hero Banner',
    description: 'Full-width banner with headline and call-to-action',
    icon: 'layout',
  },
  {
    type: 'ABOUT',
    label: 'About Me',
    description: 'Tell visitors about yourself with text and an image',
    icon: 'user',
  },
  {
    type: 'SERVICES',
    label: 'Services',
    description: 'Showcase the services you offer',
    icon: 'briefcase',
  },
  {
    type: 'GALLERY',
    label: 'Gallery',
    description: 'Photo gallery from your profile or custom images',
    icon: 'image',
  },
  {
    type: 'TESTIMONIALS',
    label: 'Testimonials',
    description: 'Client testimonials and reviews',
    icon: 'quote',
  },
  {
    type: 'BLOG',
    label: 'Blog Posts',
    description: 'Display your latest blog posts',
    icon: 'file-text',
  },
  {
    type: 'CONTACT',
    label: 'Contact',
    description: 'Contact form and details',
    icon: 'mail',
  },
  {
    type: 'CUSTOM_TEXT',
    label: 'Custom Text',
    description: 'Free-form rich text content',
    icon: 'type',
  },
  {
    type: 'VIDEO',
    label: 'Video',
    description: 'Embed a video with optional caption',
    icon: 'play',
  },
  {
    type: 'PRICING',
    label: 'Pricing',
    description: 'Display pricing plans and packages',
    icon: 'pound-sterling',
  },
  {
    type: 'FAQ',
    label: 'FAQ',
    description: 'Frequently asked questions accordion',
    icon: 'help-circle',
  },
  {
    type: 'CTA',
    label: 'Call to Action',
    description: 'Attention-grabbing CTA banner',
    icon: 'megaphone',
  },
  {
    type: 'SOCIAL_LINKS',
    label: 'Social Links',
    description: 'Links to your social media profiles',
    icon: 'share-2',
  },
  {
    type: 'SHOP',
    label: 'Shop',
    description: 'Display your products for sale',
    icon: 'shopping-bag',
  },
];
