/**
 * McCance & Widdowson's-style raw ingredient data
 * Common UK foods with nutritional values per 100g
 * Based on publicly available nutritional reference data
 */

export interface UKFoodItem {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fibre: number;
}

export const ukFoodData: UKFoodItem[] = [
  // ===== MEAT & POULTRY =====
  {
    name: "Chicken Breast, raw",
    calories: 106,
    protein: 24,
    carbs: 0,
    fat: 1.1,
    fibre: 0,
  },
  {
    name: "Chicken Thigh, raw",
    calories: 177,
    protein: 17.3,
    carbs: 0,
    fat: 12.1,
    fibre: 0,
  },
  {
    name: "Chicken Drumstick, raw",
    calories: 161,
    protein: 18,
    carbs: 0,
    fat: 9.5,
    fibre: 0,
  },
  {
    name: "Chicken Mince, raw",
    calories: 143,
    protein: 17.4,
    carbs: 0,
    fat: 8.1,
    fibre: 0,
  },
  {
    name: "Turkey Breast, raw",
    calories: 104,
    protein: 23.5,
    carbs: 0,
    fat: 0.7,
    fibre: 0,
  },
  {
    name: "Turkey Mince, raw",
    calories: 148,
    protein: 19.5,
    carbs: 0,
    fat: 7.8,
    fibre: 0,
  },
  {
    name: "Beef Mince, lean (5% fat), raw",
    calories: 137,
    protein: 21.4,
    carbs: 0,
    fat: 5.7,
    fibre: 0,
  },
  {
    name: "Beef Mince (10% fat), raw",
    calories: 176,
    protein: 19.4,
    carbs: 0,
    fat: 10.8,
    fibre: 0,
  },
  {
    name: "Beef Mince (20% fat), raw",
    calories: 243,
    protein: 17,
    carbs: 0,
    fat: 19.5,
    fibre: 0,
  },
  {
    name: "Beef Steak, sirloin, raw",
    calories: 163,
    protein: 21.3,
    carbs: 0,
    fat: 8.6,
    fibre: 0,
  },
  {
    name: "Beef Steak, fillet, raw",
    calories: 136,
    protein: 22,
    carbs: 0,
    fat: 5.1,
    fibre: 0,
  },
  {
    name: "Beef Stewing Steak, raw",
    calories: 138,
    protein: 20.2,
    carbs: 0,
    fat: 6.3,
    fibre: 0,
  },
  {
    name: "Lamb Chop, raw",
    calories: 230,
    protein: 16.5,
    carbs: 0,
    fat: 18.3,
    fibre: 0,
  },
  {
    name: "Lamb Mince, raw",
    calories: 207,
    protein: 17,
    carbs: 0,
    fat: 15.3,
    fibre: 0,
  },
  {
    name: "Lamb Leg, raw",
    calories: 162,
    protein: 19.7,
    carbs: 0,
    fat: 9.1,
    fibre: 0,
  },
  {
    name: "Pork Loin, raw",
    calories: 147,
    protein: 21.4,
    carbs: 0,
    fat: 6.9,
    fibre: 0,
  },
  {
    name: "Pork Chop, raw",
    calories: 171,
    protein: 20.7,
    carbs: 0,
    fat: 9.7,
    fibre: 0,
  },
  {
    name: "Pork Mince, raw",
    calories: 178,
    protein: 18.8,
    carbs: 0,
    fat: 11.2,
    fibre: 0,
  },
  {
    name: "Pork Belly, raw",
    calories: 374,
    protein: 14,
    carbs: 0,
    fat: 35.5,
    fibre: 0,
  },
  {
    name: "Bacon, back, raw",
    calories: 215,
    protein: 17.3,
    carbs: 0,
    fat: 16.2,
    fibre: 0,
  },
  {
    name: "Bacon, streaky, raw",
    calories: 276,
    protein: 14.3,
    carbs: 0,
    fat: 24.3,
    fibre: 0,
  },
  {
    name: "Sausages, pork, raw",
    calories: 271,
    protein: 12.6,
    carbs: 9.5,
    fat: 20.3,
    fibre: 0.7,
  },
  {
    name: "Venison, raw",
    calories: 120,
    protein: 22.2,
    carbs: 0,
    fat: 3.4,
    fibre: 0,
  },

  // ===== FISH & SEAFOOD =====
  {
    name: "Salmon Fillet, raw",
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.6,
    fibre: 0,
  },
  {
    name: "Smoked Salmon",
    calories: 183,
    protein: 24.2,
    carbs: 0,
    fat: 9.5,
    fibre: 0,
  },
  {
    name: "Cod Fillet, raw",
    calories: 80,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fibre: 0,
  },
  {
    name: "Haddock Fillet, raw",
    calories: 81,
    protein: 19.1,
    carbs: 0,
    fat: 0.6,
    fibre: 0,
  },
  {
    name: "Sea Bass, raw",
    calories: 97,
    protein: 18.4,
    carbs: 0,
    fat: 2.5,
    fibre: 0,
  },
  {
    name: "Tuna Steak, raw",
    calories: 108,
    protein: 23.4,
    carbs: 0,
    fat: 1,
    fibre: 0,
  },
  {
    name: "Tuna, tinned in spring water",
    calories: 99,
    protein: 23.5,
    carbs: 0,
    fat: 0.6,
    fibre: 0,
  },
  {
    name: "Tuna, tinned in oil",
    calories: 189,
    protein: 25.5,
    carbs: 0,
    fat: 9.3,
    fibre: 0,
  },
  {
    name: "Mackerel, raw",
    calories: 205,
    protein: 18.6,
    carbs: 0,
    fat: 14.1,
    fibre: 0,
  },
  {
    name: "Mackerel, smoked",
    calories: 305,
    protein: 20.3,
    carbs: 0,
    fat: 24.9,
    fibre: 0,
  },
  {
    name: "Sardines, tinned in oil",
    calories: 208,
    protein: 24.6,
    carbs: 0,
    fat: 11.5,
    fibre: 0,
  },
  {
    name: "Prawns, raw",
    calories: 71,
    protein: 16.5,
    carbs: 0,
    fat: 0.6,
    fibre: 0,
  },
  {
    name: "King Prawns, raw",
    calories: 69,
    protein: 15.4,
    carbs: 0,
    fat: 0.6,
    fibre: 0,
  },
  {
    name: "Trout, raw",
    calories: 119,
    protein: 20.5,
    carbs: 0,
    fat: 3.9,
    fibre: 0,
  },
  {
    name: "Plaice, raw",
    calories: 79,
    protein: 17.1,
    carbs: 0,
    fat: 1.1,
    fibre: 0,
  },

  // ===== DAIRY & EGGS =====
  {
    name: "Whole Milk",
    calories: 66,
    protein: 3.3,
    carbs: 4.7,
    fat: 3.7,
    fibre: 0,
  },
  {
    name: "Semi-Skimmed Milk",
    calories: 46,
    protein: 3.4,
    carbs: 4.8,
    fat: 1.7,
    fibre: 0,
  },
  {
    name: "Skimmed Milk",
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fibre: 0,
  },
  {
    name: "Oat Milk",
    calories: 44,
    protein: 0.4,
    carbs: 6.7,
    fat: 1.5,
    fibre: 0.1,
  },
  {
    name: "Almond Milk, unsweetened",
    calories: 13,
    protein: 0.4,
    carbs: 0,
    fat: 1.1,
    fibre: 0.2,
  },
  {
    name: "Soya Milk, unsweetened",
    calories: 33,
    protein: 3.3,
    carbs: 0.5,
    fat: 1.8,
    fibre: 0.5,
  },
  {
    name: "Cheddar Cheese",
    calories: 416,
    protein: 25.4,
    carbs: 0.1,
    fat: 34.9,
    fibre: 0,
  },
  {
    name: "Mozzarella",
    calories: 280,
    protein: 22.2,
    carbs: 2.2,
    fat: 20.3,
    fibre: 0,
  },
  {
    name: "Parmesan",
    calories: 415,
    protein: 35.8,
    carbs: 0.1,
    fat: 29.7,
    fibre: 0,
  },
  {
    name: "Feta Cheese",
    calories: 250,
    protein: 15.6,
    carbs: 1.5,
    fat: 20.2,
    fibre: 0,
  },
  {
    name: "Cottage Cheese",
    calories: 98,
    protein: 11.1,
    carbs: 3.4,
    fat: 4.3,
    fibre: 0,
  },
  {
    name: "Cream Cheese",
    calories: 249,
    protein: 5.9,
    carbs: 3.5,
    fat: 24,
    fibre: 0,
  },
  {
    name: "Greek Yoghurt, full fat",
    calories: 133,
    protein: 5.7,
    carbs: 4.7,
    fat: 10.2,
    fibre: 0,
  },
  {
    name: "Greek Yoghurt, 0% fat",
    calories: 57,
    protein: 10.3,
    carbs: 4,
    fat: 0,
    fibre: 0,
  },
  {
    name: "Natural Yoghurt",
    calories: 79,
    protein: 5.7,
    carbs: 7.8,
    fat: 3,
    fibre: 0,
  },
  {
    name: "Double Cream",
    calories: 449,
    protein: 1.7,
    carbs: 2.6,
    fat: 48,
    fibre: 0,
  },
  {
    name: "Single Cream",
    calories: 193,
    protein: 2.6,
    carbs: 4.1,
    fat: 18.1,
    fibre: 0,
  },
  {
    name: "Eggs, whole, raw",
    calories: 131,
    protein: 12.6,
    carbs: 0,
    fat: 9.0,
    fibre: 0,
  },
  {
    name: "Egg White, raw",
    calories: 49,
    protein: 10.8,
    carbs: 0.7,
    fat: 0.2,
    fibre: 0,
  },
  {
    name: "Butter, salted",
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.1,
    fibre: 0,
  },
  {
    name: "Butter, unsalted",
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.1,
    fibre: 0,
  },

  // ===== VEGETABLES =====
  {
    name: "Broccoli, raw",
    calories: 33,
    protein: 4.4,
    carbs: 1.8,
    fat: 0.9,
    fibre: 2.6,
  },
  {
    name: "Cauliflower, raw",
    calories: 28,
    protein: 2.9,
    carbs: 2.1,
    fat: 0.9,
    fibre: 1.8,
  },
  {
    name: "Carrots, raw",
    calories: 35,
    protein: 0.6,
    carbs: 7.9,
    fat: 0.3,
    fibre: 2.4,
  },
  {
    name: "Spinach, raw",
    calories: 25,
    protein: 2.8,
    carbs: 1.6,
    fat: 0.8,
    fibre: 2.1,
  },
  {
    name: "Kale, raw",
    calories: 33,
    protein: 2.9,
    carbs: 1.4,
    fat: 1.4,
    fibre: 3.6,
  },
  {
    name: "Potato, raw",
    calories: 75,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fibre: 1.3,
  },
  {
    name: "Sweet Potato, raw",
    calories: 87,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fibre: 3,
  },
  {
    name: "Courgette, raw",
    calories: 18,
    protein: 1.2,
    carbs: 1.8,
    fat: 0.4,
    fibre: 1,
  },
  {
    name: "Aubergine, raw",
    calories: 15,
    protein: 1,
    carbs: 2.2,
    fat: 0.2,
    fibre: 2,
  },
  {
    name: "Red Pepper, raw",
    calories: 32,
    protein: 1,
    carbs: 6.4,
    fat: 0.3,
    fibre: 1.4,
  },
  {
    name: "Green Pepper, raw",
    calories: 15,
    protein: 0.8,
    carbs: 2.6,
    fat: 0.3,
    fibre: 1.6,
  },
  {
    name: "Onion, raw",
    calories: 36,
    protein: 1.2,
    carbs: 7.9,
    fat: 0.2,
    fibre: 1.4,
  },
  {
    name: "Red Onion, raw",
    calories: 37,
    protein: 1.2,
    carbs: 8.1,
    fat: 0.2,
    fibre: 1.4,
  },
  {
    name: "Spring Onion, raw",
    calories: 23,
    protein: 2,
    carbs: 3,
    fat: 0.5,
    fibre: 1.5,
  },
  {
    name: "Garlic, raw",
    calories: 98,
    protein: 7.9,
    carbs: 16.3,
    fat: 0.6,
    fibre: 4.7,
  },
  {
    name: "Mushrooms, raw",
    calories: 13,
    protein: 1.8,
    carbs: 0.4,
    fat: 0.5,
    fibre: 1.1,
  },
  {
    name: "Tomato, raw",
    calories: 17,
    protein: 0.7,
    carbs: 3.1,
    fat: 0.3,
    fibre: 1,
  },
  {
    name: "Cherry Tomatoes",
    calories: 20,
    protein: 0.9,
    carbs: 3.5,
    fat: 0.3,
    fibre: 1.2,
  },
  {
    name: "Cucumber, raw",
    calories: 10,
    protein: 0.7,
    carbs: 1.5,
    fat: 0.1,
    fibre: 0.6,
  },
  {
    name: "Lettuce, iceberg",
    calories: 14,
    protein: 0.7,
    carbs: 1.8,
    fat: 0.3,
    fibre: 0.5,
  },
  {
    name: "Lettuce, romaine",
    calories: 14,
    protein: 1.2,
    carbs: 1.2,
    fat: 0.3,
    fibre: 1.7,
  },
  {
    name: "Rocket",
    calories: 25,
    protein: 2.6,
    carbs: 2,
    fat: 0.7,
    fibre: 1.6,
  },
  {
    name: "Watercress",
    calories: 22,
    protein: 3,
    carbs: 0.4,
    fat: 1,
    fibre: 1.5,
  },
  {
    name: "Celery, raw",
    calories: 7,
    protein: 0.7,
    carbs: 0.9,
    fat: 0.2,
    fibre: 1.1,
  },
  {
    name: "Sweetcorn, raw",
    calories: 86,
    protein: 3.2,
    carbs: 16.3,
    fat: 1.2,
    fibre: 2.7,
  },
  {
    name: "Sweetcorn, tinned",
    calories: 79,
    protein: 2.7,
    carbs: 15.3,
    fat: 1.1,
    fibre: 1.5,
  },
  {
    name: "Green Beans, raw",
    calories: 24,
    protein: 1.7,
    carbs: 3.2,
    fat: 0.5,
    fibre: 2.5,
  },
  {
    name: "Peas, raw",
    calories: 83,
    protein: 6.9,
    carbs: 11,
    fat: 1.5,
    fibre: 4.7,
  },
  {
    name: "Peas, frozen",
    calories: 72,
    protein: 5.6,
    carbs: 9.3,
    fat: 0.9,
    fibre: 4.5,
  },
  {
    name: "Asparagus, raw",
    calories: 25,
    protein: 2.9,
    carbs: 2,
    fat: 0.6,
    fibre: 2.1,
  },
  {
    name: "Beetroot, raw",
    calories: 36,
    protein: 1.7,
    carbs: 7.6,
    fat: 0.1,
    fibre: 1.9,
  },
  {
    name: "Butternut Squash, raw",
    calories: 36,
    protein: 0.9,
    carbs: 7.4,
    fat: 0.1,
    fibre: 1.5,
  },
  {
    name: "Cabbage, raw",
    calories: 26,
    protein: 1.3,
    carbs: 4.9,
    fat: 0.2,
    fibre: 2.2,
  },
  {
    name: "Leek, raw",
    calories: 22,
    protein: 1.6,
    carbs: 2.9,
    fat: 0.7,
    fibre: 1.8,
  },
  {
    name: "Parsnip, raw",
    calories: 66,
    protein: 1.3,
    carbs: 12.5,
    fat: 1.1,
    fibre: 4.3,
  },
  {
    name: "Turnip, raw",
    calories: 23,
    protein: 0.7,
    carbs: 4.6,
    fat: 0.2,
    fibre: 1.5,
  },

  // ===== FRUITS =====
  {
    name: "Apple",
    calories: 49,
    protein: 0.4,
    carbs: 11.8,
    fat: 0.1,
    fibre: 1.8,
  },
  {
    name: "Banana",
    calories: 95,
    protein: 1.2,
    carbs: 22.8,
    fat: 0.3,
    fibre: 1.1,
  },
  {
    name: "Orange",
    calories: 37,
    protein: 1.1,
    carbs: 8.5,
    fat: 0.1,
    fibre: 1.7,
  },
  {
    name: "Satsuma",
    calories: 36,
    protein: 0.9,
    carbs: 8.7,
    fat: 0.1,
    fibre: 1.3,
  },
  {
    name: "Strawberries",
    calories: 27,
    protein: 0.8,
    carbs: 6,
    fat: 0.1,
    fibre: 1.1,
  },
  {
    name: "Blueberries",
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fibre: 1.5,
  },
  {
    name: "Raspberries",
    calories: 40,
    protein: 1.4,
    carbs: 4.6,
    fat: 0.6,
    fibre: 2.5,
  },
  {
    name: "Blackberries",
    calories: 25,
    protein: 0.9,
    carbs: 5.1,
    fat: 0.2,
    fibre: 3.1,
  },
  {
    name: "Grapes",
    calories: 60,
    protein: 0.4,
    carbs: 15.4,
    fat: 0.1,
    fibre: 0.7,
  },
  {
    name: "Pear",
    calories: 40,
    protein: 0.3,
    carbs: 10.0,
    fat: 0.1,
    fibre: 2.2,
  },
  {
    name: "Mango",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.2,
    fibre: 1.5,
  },
  {
    name: "Pineapple",
    calories: 42,
    protein: 0.4,
    carbs: 10.1,
    fat: 0.2,
    fibre: 1,
  },
  {
    name: "Watermelon",
    calories: 31,
    protein: 0.5,
    carbs: 7.6,
    fat: 0.3,
    fibre: 0.1,
  },
  {
    name: "Kiwi",
    calories: 49,
    protein: 1.1,
    carbs: 10.6,
    fat: 0.4,
    fibre: 1.9,
  },
  { name: "Peach", calories: 33, protein: 1, carbs: 7.6, fat: 0.1, fibre: 1.5 },
  {
    name: "Plum",
    calories: 36,
    protein: 0.6,
    carbs: 8.8,
    fat: 0.1,
    fibre: 1.5,
  },
  {
    name: "Avocado",
    calories: 190,
    protein: 1.9,
    carbs: 1.9,
    fat: 19.5,
    fibre: 3.4,
  },
  { name: "Lemon", calories: 20, protein: 1, carbs: 3.2, fat: 0.3, fibre: 4.7 },
  { name: "Lime", calories: 9, protein: 0.5, carbs: 1.6, fat: 0.1, fibre: 1.9 },
  {
    name: "Melon, cantaloupe",
    calories: 19,
    protein: 0.7,
    carbs: 4.2,
    fat: 0.1,
    fibre: 0.3,
  },
  {
    name: "Melon, honeydew",
    calories: 28,
    protein: 0.4,
    carbs: 6.6,
    fat: 0.1,
    fibre: 0.5,
  },
  {
    name: "Cherries",
    calories: 48,
    protein: 0.9,
    carbs: 11.5,
    fat: 0.1,
    fibre: 0.9,
  },
  {
    name: "Pomegranate Seeds",
    calories: 83,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    fibre: 4,
  },
  {
    name: "Dried Dates",
    calories: 282,
    protein: 2.8,
    carbs: 68.3,
    fat: 0.4,
    fibre: 8,
  },
  {
    name: "Raisins",
    calories: 296,
    protein: 2.5,
    carbs: 69.4,
    fat: 0.4,
    fibre: 2,
  },
  {
    name: "Dried Apricots",
    calories: 188,
    protein: 3.4,
    carbs: 43.4,
    fat: 0.5,
    fibre: 6.3,
  },

  // ===== GRAINS & CEREALS =====
  {
    name: "White Rice, dry",
    calories: 356,
    protein: 6.7,
    carbs: 78.9,
    fat: 0.4,
    fibre: 0.4,
  },
  {
    name: "Brown Rice, dry",
    calories: 357,
    protein: 7.5,
    carbs: 76.2,
    fat: 2.7,
    fibre: 3.4,
  },
  {
    name: "Basmati Rice, dry",
    calories: 349,
    protein: 7.5,
    carbs: 77.8,
    fat: 0.6,
    fibre: 0.6,
  },
  {
    name: "Pasta, white, dry",
    calories: 350,
    protein: 12.5,
    carbs: 71.5,
    fat: 1.8,
    fibre: 2.9,
  },
  {
    name: "Pasta, wholewheat, dry",
    calories: 324,
    protein: 13.4,
    carbs: 61.3,
    fat: 2.5,
    fibre: 8.2,
  },
  {
    name: "Egg Noodles, dry",
    calories: 384,
    protein: 12.8,
    carbs: 69,
    fat: 4.4,
    fibre: 2.7,
  },
  {
    name: "Couscous, dry",
    calories: 356,
    protein: 12.8,
    carbs: 72.4,
    fat: 1.8,
    fibre: 2,
  },
  {
    name: "Quinoa, dry",
    calories: 368,
    protein: 14.1,
    carbs: 64.2,
    fat: 6.1,
    fibre: 7,
  },
  {
    name: "Bulgur Wheat, dry",
    calories: 342,
    protein: 12.3,
    carbs: 63.4,
    fat: 1.3,
    fibre: 12.5,
  },
  {
    name: "Porridge Oats",
    calories: 375,
    protein: 11,
    carbs: 60.4,
    fat: 8.7,
    fibre: 8.5,
  },
  {
    name: "Wholemeal Bread",
    calories: 224,
    protein: 9.4,
    carbs: 38.6,
    fat: 2.5,
    fibre: 5.8,
  },
  {
    name: "White Bread",
    calories: 240,
    protein: 8.4,
    carbs: 46.1,
    fat: 1.6,
    fibre: 2.9,
  },
  {
    name: "Sourdough Bread",
    calories: 234,
    protein: 8.8,
    carbs: 43.9,
    fat: 1.6,
    fibre: 2.1,
  },
  {
    name: "Pitta Bread, white",
    calories: 255,
    protein: 8.7,
    carbs: 50.7,
    fat: 1.2,
    fibre: 2.2,
  },
  {
    name: "Naan Bread",
    calories: 310,
    protein: 8.8,
    carbs: 48.3,
    fat: 9.5,
    fibre: 2.1,
  },
  {
    name: "Wrap, flour tortilla",
    calories: 312,
    protein: 8.3,
    carbs: 50.6,
    fat: 8.6,
    fibre: 2.2,
  },
  {
    name: "Rice Cakes",
    calories: 387,
    protein: 7.8,
    carbs: 81.5,
    fat: 2.8,
    fibre: 1.8,
  },
  { name: "Crumpet", calories: 198, protein: 6, carbs: 38, fat: 1, fibre: 1.5 },
  {
    name: "Bagel, plain",
    calories: 257,
    protein: 10,
    carbs: 49.2,
    fat: 1.6,
    fibre: 2.3,
  },

  // ===== LEGUMES & PULSES =====
  {
    name: "Chickpeas, tinned",
    calories: 115,
    protein: 7.2,
    carbs: 16.1,
    fat: 2.6,
    fibre: 4.3,
  },
  {
    name: "Chickpeas, dry",
    calories: 364,
    protein: 19,
    carbs: 60.6,
    fat: 6,
    fibre: 17.4,
  },
  {
    name: "Red Lentils, dry",
    calories: 318,
    protein: 23.8,
    carbs: 52.3,
    fat: 1.3,
    fibre: 4.9,
  },
  {
    name: "Green Lentils, dry",
    calories: 297,
    protein: 24.3,
    carbs: 48.8,
    fat: 1.1,
    fibre: 8.9,
  },
  {
    name: "Kidney Beans, tinned",
    calories: 100,
    protein: 6.9,
    carbs: 14.8,
    fat: 0.5,
    fibre: 6.2,
  },
  {
    name: "Black Beans, tinned",
    calories: 97,
    protein: 6.4,
    carbs: 14.1,
    fat: 0.5,
    fibre: 6,
  },
  {
    name: "Baked Beans, tinned",
    calories: 81,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.4,
    fibre: 3.7,
  },
  {
    name: "Butter Beans, tinned",
    calories: 77,
    protein: 5.4,
    carbs: 11.7,
    fat: 0.4,
    fibre: 4.6,
  },
  {
    name: "Cannellini Beans, tinned",
    calories: 92,
    protein: 6.4,
    carbs: 13.5,
    fat: 0.4,
    fibre: 4.3,
  },
  {
    name: "Edamame Beans",
    calories: 122,
    protein: 11.9,
    carbs: 8.9,
    fat: 5.2,
    fibre: 5.2,
  },
  {
    name: "Garden Peas, frozen",
    calories: 72,
    protein: 5.6,
    carbs: 9.3,
    fat: 0.9,
    fibre: 4.5,
  },
  {
    name: "Tofu, firm",
    calories: 117,
    protein: 12.7,
    carbs: 2.3,
    fat: 6.6,
    fibre: 0.3,
  },
  {
    name: "Tempeh",
    calories: 193,
    protein: 20.3,
    carbs: 7.6,
    fat: 10.8,
    fibre: 0,
  },

  // ===== NUTS & SEEDS =====
  {
    name: "Almonds",
    calories: 575,
    protein: 21.2,
    carbs: 6.9,
    fat: 49.4,
    fibre: 12.2,
  },
  {
    name: "Cashew Nuts",
    calories: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.9,
    fibre: 3.3,
  },
  {
    name: "Peanuts, raw",
    calories: 567,
    protein: 25.8,
    carbs: 16.1,
    fat: 49.2,
    fibre: 8.5,
  },
  {
    name: "Walnuts",
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fibre: 6.7,
  },
  {
    name: "Pecans",
    calories: 691,
    protein: 9.2,
    carbs: 13.9,
    fat: 72,
    fibre: 9.6,
  },
  {
    name: "Brazil Nuts",
    calories: 656,
    protein: 14.3,
    carbs: 12.3,
    fat: 66.4,
    fibre: 7.5,
  },
  {
    name: "Macadamia Nuts",
    calories: 718,
    protein: 7.9,
    carbs: 13.8,
    fat: 75.8,
    fibre: 8.6,
  },
  {
    name: "Pistachios",
    calories: 560,
    protein: 20.2,
    carbs: 27.2,
    fat: 45.3,
    fibre: 10.6,
  },
  {
    name: "Pine Nuts",
    calories: 673,
    protein: 13.7,
    carbs: 13.1,
    fat: 68.4,
    fibre: 3.7,
  },
  {
    name: "Mixed Nuts",
    calories: 607,
    protein: 18,
    carbs: 16,
    fat: 54,
    fibre: 7,
  },
  {
    name: "Chia Seeds",
    calories: 486,
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    fibre: 34.4,
  },
  {
    name: "Flaxseed (Linseed)",
    calories: 534,
    protein: 18.3,
    carbs: 28.9,
    fat: 42.2,
    fibre: 27.3,
  },
  {
    name: "Sunflower Seeds",
    calories: 584,
    protein: 20.8,
    carbs: 20,
    fat: 51.5,
    fibre: 8.6,
  },
  {
    name: "Pumpkin Seeds",
    calories: 559,
    protein: 30.2,
    carbs: 10.7,
    fat: 49.1,
    fibre: 6,
  },
  {
    name: "Sesame Seeds",
    calories: 573,
    protein: 17.7,
    carbs: 23.4,
    fat: 49.7,
    fibre: 11.8,
  },

  // ===== OILS & FATS =====
  {
    name: "Olive Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fibre: 0,
  },
  {
    name: "Coconut Oil",
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fibre: 0,
  },
  {
    name: "Rapeseed Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fibre: 0,
  },
  {
    name: "Sunflower Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fibre: 0,
  },
  {
    name: "Sesame Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fibre: 0,
  },

  // ===== SPREADS & CONDIMENTS =====
  {
    name: "Peanut Butter, smooth",
    calories: 588,
    protein: 25.1,
    carbs: 13.8,
    fat: 49.4,
    fibre: 5.4,
  },
  {
    name: "Peanut Butter, crunchy",
    calories: 590,
    protein: 24.9,
    carbs: 14.1,
    fat: 49.8,
    fibre: 6.3,
  },
  {
    name: "Almond Butter",
    calories: 614,
    protein: 21,
    carbs: 18.8,
    fat: 55.5,
    fibre: 3.7,
  },
  {
    name: "Hummus",
    calories: 187,
    protein: 7.4,
    carbs: 11.6,
    fat: 12.6,
    fibre: 3.7,
  },
  {
    name: "Tahini",
    calories: 595,
    protein: 17,
    carbs: 21.2,
    fat: 53.8,
    fibre: 9.3,
  },
  { name: "Honey", calories: 334, protein: 0.4, carbs: 81.1, fat: 0, fibre: 0 },
  {
    name: "Maple Syrup",
    calories: 260,
    protein: 0,
    carbs: 67,
    fat: 0.1,
    fibre: 0,
  },
  {
    name: "Jam, strawberry",
    calories: 244,
    protein: 0.4,
    carbs: 60,
    fat: 0.1,
    fibre: 0.9,
  },
  {
    name: "Marmalade",
    calories: 261,
    protein: 0.1,
    carbs: 69.5,
    fat: 0,
    fibre: 0.7,
  },
  {
    name: "Marmite",
    calories: 252,
    protein: 38.8,
    carbs: 19.7,
    fat: 0.4,
    fibre: 3,
  },

  // ===== BAKING & STAPLES =====
  {
    name: "Plain Flour",
    calories: 341,
    protein: 9.4,
    carbs: 73.3,
    fat: 1.2,
    fibre: 3.1,
  },
  {
    name: "Self-Raising Flour",
    calories: 330,
    protein: 8.9,
    carbs: 72.1,
    fat: 1,
    fibre: 2.4,
  },
  {
    name: "Wholemeal Flour",
    calories: 310,
    protein: 12.6,
    carbs: 61.8,
    fat: 2.2,
    fibre: 9,
  },
  {
    name: "Cornflour",
    calories: 355,
    protein: 0.3,
    carbs: 87.5,
    fat: 0.5,
    fibre: 0.9,
  },
  {
    name: "Caster Sugar",
    calories: 400,
    protein: 0,
    carbs: 100,
    fat: 0,
    fibre: 0,
  },
  {
    name: "Brown Sugar",
    calories: 380,
    protein: 0.1,
    carbs: 97.3,
    fat: 0,
    fibre: 0,
  },
  {
    name: "Cocoa Powder",
    calories: 228,
    protein: 19.6,
    carbs: 11.5,
    fat: 13.7,
    fibre: 33.2,
  },
  {
    name: "Dark Chocolate, 70%",
    calories: 530,
    protein: 7.8,
    carbs: 48,
    fat: 34,
    fibre: 7.5,
  },
  {
    name: "Milk Chocolate",
    calories: 535,
    protein: 7.7,
    carbs: 56.5,
    fat: 30.7,
    fibre: 2.4,
  },
  {
    name: "White Chocolate",
    calories: 539,
    protein: 5.9,
    carbs: 59.2,
    fat: 32.1,
    fibre: 0.2,
  },
  {
    name: "Desiccated Coconut",
    calories: 604,
    protein: 5.6,
    carbs: 6.4,
    fat: 62,
    fibre: 13.7,
  },

  // ===== PROTEIN SUPPLEMENTS =====
  {
    name: "Whey Protein Powder",
    calories: 375,
    protein: 78,
    carbs: 8,
    fat: 3.5,
    fibre: 0,
  },
  {
    name: "Casein Protein Powder",
    calories: 360,
    protein: 75,
    carbs: 6,
    fat: 3,
    fibre: 0,
  },
  {
    name: "Pea Protein Powder",
    calories: 370,
    protein: 80,
    carbs: 4,
    fat: 2.5,
    fibre: 5,
  },

  // ===== COMMON PREPARED / MISC =====
  {
    name: "Tinned Chopped Tomatoes",
    calories: 17,
    protein: 0.9,
    carbs: 3,
    fat: 0.1,
    fibre: 0.9,
  },
  {
    name: "Tomato Passata",
    calories: 24,
    protein: 1.3,
    carbs: 3.5,
    fat: 0.2,
    fibre: 1.2,
  },
  {
    name: "Tomato Puree",
    calories: 76,
    protein: 4.3,
    carbs: 13.1,
    fat: 0.5,
    fibre: 3.4,
  },
  {
    name: "Coconut Milk, tinned",
    calories: 197,
    protein: 2.2,
    carbs: 2.7,
    fat: 19.6,
    fibre: 0,
  },
  {
    name: "Coconut Cream",
    calories: 330,
    protein: 3.6,
    carbs: 6.5,
    fat: 34,
    fibre: 0,
  },
  {
    name: "Soy Sauce",
    calories: 53,
    protein: 8.1,
    carbs: 4.9,
    fat: 0,
    fibre: 0.8,
  },
  {
    name: "Mayonnaise",
    calories: 691,
    protein: 1.1,
    carbs: 1.6,
    fat: 75.6,
    fibre: 0,
  },
  {
    name: "Ketchup",
    calories: 101,
    protein: 1.2,
    carbs: 24,
    fat: 0.1,
    fibre: 0.3,
  },
  {
    name: "Balsamic Vinegar",
    calories: 88,
    protein: 0.5,
    carbs: 17.0,
    fat: 0,
    fibre: 0,
  },
  {
    name: "Apple Cider Vinegar",
    calories: 21,
    protein: 0,
    carbs: 0.9,
    fat: 0,
    fibre: 0,
  },
  {
    name: "Stock Cube, chicken",
    calories: 219,
    protein: 15.2,
    carbs: 17.2,
    fat: 10.6,
    fibre: 0.5,
  },
  {
    name: "Gravy Granules",
    calories: 354,
    protein: 5.8,
    carbs: 49.2,
    fat: 14.7,
    fibre: 1.3,
  },
  {
    name: "Muesli",
    calories: 363,
    protein: 9.8,
    carbs: 66.2,
    fat: 6.2,
    fibre: 7.6,
  },
  { name: "Granola", calories: 471, protein: 10, carbs: 58, fat: 21, fibre: 5 },
  {
    name: "Cornflakes",
    calories: 376,
    protein: 7,
    carbs: 84,
    fat: 0.9,
    fibre: 3,
  },
  {
    name: "Weetabix",
    calories: 362,
    protein: 11.5,
    carbs: 68,
    fat: 2.7,
    fibre: 10,
  },
];
