// =============================================================================
// RE-EXPORT PRISMA TYPES
// =============================================================================
// Types are generated by Prisma and zod-prisma-types.
// This package re-exports them for convenience.

export type {
  User,
  Session,
  Account,
  Verification,
  TrainerProfile,
  ContactRequest,
  ProfileView,
  NewsletterSubscription,
  UserRole,
  SubscriptionTier,
  TravelOption,
  ContactRequestType,
  ContactRequestStatus,
} from '@fitnassist/database';

// =============================================================================
// UTILITY TYPES
// =============================================================================
// These are additional types not generated by Prisma

export * from './common.types';
export * from './sse.types';
