export { prisma } from './client';

// Re-export Prisma types and client
export {
  PrismaClient,
  Prisma,
  // Enums
  UserRole,
  SubscriptionTier,
  TravelOption,
  ContactRequestType,
  ContactRequestStatus,
  Gender,
  UnitPreference,
  ExperienceLevel,
  ActivityLevel,
  ClientStatus,
  OnboardingStatus,
  MuscleGroup,
  MealType,
  DiaryEntryType,
  MoodLevel,
  GoalType,
  GoalStatus,
  SubscriptionStatus,
  BillingPeriod,
  BookingStatus,
  DayOfWeek,
  NotificationType,
  ActivityType,
  ActivitySource,
  PersonalBestCategory,
  Visibility,
  FriendshipStatus,
  PostType,
  BookingSuggestionStatus,
  SessionType,
  PaymentStatus,
  ReportReason,
} from '@prisma/client';

// Re-export model types with explicit names to avoid conflicts
export type {
  User,
  Session,
  Account,
  Verification,
  TrainerProfile,
  TraineeProfile,
  ContactRequest,
  ClientRoster,
  ClientNote,
  ConversationPreference,
  Exercise,
  Recipe,
  WorkoutPlan,
  WorkoutExercise,
  MealPlan,
  MealPlanRecipe,
  GalleryImage,
  ProfileView,
  NewsletterSubscription,
  OnboardingTemplate,
  OnboardingResponse,
  DiaryEntry,
  WeightEntry,
  WaterEntry,
  MeasurementEntry,
  MoodEntry,
  SleepEntry,
  FoodEntry,
  WorkoutLogEntry,
  StepsEntry,
  ProgressPhoto,
  DiaryComment,
  Goal,
  Subscription,
  SessionLocation,
  Availability,
  AvailabilityOverride,
  Booking,
  TravelTimeCache,
  ClientWorkoutPlanAssignment,
  ClientMealPlanAssignment,
  Message,
  Notification,
  PushSubscription,
  ActivityEntry,
  PersonalBest,
  Follow,
  Friendship,
  Post,
  PostLike,
  DiaryEntryLike,
  BookingSuggestion,
  UserBadge,
  SessionPrice,
  CancellationPolicy,
  SessionPayment,
  Review,
  ReviewReport,
} from '@prisma/client';

// Re-export generated Zod schemas from model schemas
export * from './generated/zod/modelSchema';

// Re-export enum schemas (excluding problematic JSON types)
export {
  UserRoleSchema,
  SubscriptionTierSchema,
  TravelOptionSchema,
  ContactRequestTypeSchema,
  ContactRequestStatusSchema,
  GenderSchema,
  UnitPreferenceSchema,
  ExperienceLevelSchema,
  ActivityLevelSchema,
  ClientStatusSchema,
  OnboardingStatusSchema,
  MuscleGroupSchema,
  MealTypeSchema,
  DiaryEntryTypeSchema,
  MoodLevelSchema,
  GoalTypeSchema,
  GoalStatusSchema,
  SubscriptionStatusSchema,
  BillingPeriodSchema,
  BookingStatusSchema,
  DayOfWeekSchema,
  NotificationTypeSchema,
  ActivityTypeSchema,
  ActivitySourceSchema,
  PersonalBestCategorySchema,
  VisibilitySchema,
  PostTypeSchema,
  FriendshipStatusSchema,
  SessionTypeSchema,
  PaymentStatusSchema,
  ReportReasonSchema,
} from './generated/zod/inputTypeSchemas';
